#!/bin/zsh
# ------------------------------------------------------------------------------
# Description
# -----------
#
#  Completion script for VSH (vagrant sh)
#
#  Source: https://github.com/ganglio/dotfiles
#
# ------------------------------------------------------------------------------
# Authors
# -------
#
#  * Roberto Torella (https://github.com/ganglio)
#
# ------------------------------------------------------------------------------

function _vsh() {
	local -a machines
	local running

	running=$(jq -r -f ~/.dotfiles/bin/vagrants_complete.jq ~/.vagrant.d/data/machine-index/index)
	machines=("${(s/ /)running}")

	_describe 'values' machines
}

compdef _vsh vsh