#!/bin/zsh

IS_TMUX_STATUS="TRUE"
IS_CENTER="TRUE"
first=""
source ~/.dotfiles/ohmy.custom/themes/lib.zsh-theme

for win in $(tmux list-windows | awk '{print $1$2}'); do
	case $win in
		*\**) FG="black";       BG="brightyellow";;
		*)    FG="brightgreen"; BG="brightwhite";;
	esac
	if [[ -z $first ]]; then
		first='done'
		rprompt_segment $BG $FG ""
	fi
	prompt_segment $BG $FG "$(echo $win | sed "s/[#*-]//g")"
done
prompt_end
