#!/usr/bin/env python

import os
import sys

if os.name != 'posix':
	sys.exit('platform not supported')

import psutil

cpuperc = psutil.cpu_percent(interval=0.1)
cpu_dashes = "█"*int(float(cpuperc)/10)
cpu_empty  = "·"*(10-int(float(cpuperc)/10))
lines = "%s%s" % (cpu_dashes,cpu_empty)
print(lines)
