#!/usr/bin/env python
# vim: set fileencoding=utf-8 :

import os
import sys

if os.name != 'posix':
	sys.exit('platform not supported')

import psutil
import time
from lib import *

disk_before = psutil.disk_io_counters()
time.sleep(0.1)
disk_after = psutil.disk_io_counters()

written_bytes = sparkle("/tmp/diskreadhistory",str(disk_after.write_bytes - disk_before.write_bytes))
read_bytes    = sparkle("/tmp/diskwritehistory",str(disk_after.read_bytes  - disk_before.read_bytes))

if (len(sys.argv)>1 and sys.argv[1]=="read"):
	print("%s" % read_bytes)
elif (len(sys.argv)>1 and sys.argv[1]=="write"):
	print("%s" % written_bytes)
else:
	print("%s|%s" % (written_bytes,read_bytes))
