#!/bin/zsh

IS_TMUX_STATUS="TRUE"
source ~/.dotfiles/ohmy.custom/themes/lib.zsh-theme

prompt_segment black yellow '#T'
[[ -n "$(~/.dotfiles/bin/ssid)" ]] && prompt_segment black red "$(~/.dotfiles/bin/ssid)"
prompt_end
