#!/usr/bin/env python

import os
import sys

if os.name != 'posix':
	sys.exit('platform not supported')

import psutil

memperc = psutil.phymem_usage().percent
mem_dashes = "█"*round(float(memperc)/10)
mem_empty  = "·"*(10-round(float(memperc)/10))
lines = "%s%s" % (mem_dashes,mem_empty)
print(lines)
