#!/usr/bin/env python
# vim: set fileencoding=utf-8 :

import os
import sys

if os.name != 'posix':
	sys.exit('platform not supported')

import psutil
import time
from lib import *

before = psutil.net_io_counters()
time.sleep(0.1)
after = psutil.net_io_counters()

written = sparkle("/tmp/netreadhistory", str(after.bytes_sent - before.bytes_sent))
read    = sparkle("/tmp/netwritehistory",str(after.bytes_recv - before.bytes_recv))

if (len(sys.argv)>1 and sys.argv[1]=="read"):
	print("%s" % read)
elif (len(sys.argv)>1 and sys.argv[1]=="write"):
	print("%s" % written)
else:
	print("%s|%s" % (written,read))
