#!/bin/zsh

IS_TMUX_STATUS="TRUE"
source ~/.dotfiles/ohmy.custom/themes/lib.zsh-theme

# Battery widget for Mac
rprompt_battery() {
	if [[ "$OSTYPE" = darwin* ]]; then
		local smart_battery_status="$(ioreg -rc "AppleSmartBattery")"
		local plugged charge symbol

		typeset -F maxcapacity=$(echo $smart_battery_status | grep '^.*"MaxCapacity"\ =\ ' | sed -e 's/^.*"MaxCapacity"\ =\ //')
		typeset -F currentcapacity=$(echo $smart_battery_status | grep '^.*"CurrentCapacity"\ =\ ' | sed -e 's/^.*CurrentCapacity"\ =\ //')
		plugged=$(echo $smart_battery_status | grep '^.*"ExternalConnected"\ =\ ' | sed -e 's/^.*"ExternalConnected"\ =\ //')
		typeset -F charge=$(((currentcapacity/maxcapacity) * 100))

		if [[ $plugged != "Yes" ]]; then
			symbol='🔋  '
		else
			symbol=''
		fi

		if [[ $charge -gt 50 ]]; then
			color='green'
		elif [[ $charge -gt 25 ]]; then
			color='yellow'
		else
			color='red'
		fi

		if [[ $color != 'red' ]]; then
			bar=${(l.($charge/10)..■.)}${(l.(10-$charge/10)..╌.)}
		else
			bar="$charge%%"
		fi

		rprompt_segment black $color "$symbol$(printf "%2.2f%%" $charge)"
	fi
}

rprompt_online() {
	pingtime=$(ping -c 1 www.google.com 2>&1 | grep 'time' | awk -F '=' '{ print $4}')
	if [[ -n "$pingtime" ]]; then
		color='green'
	else
		color='red'
	fi

	rprompt_segment black $color "● $pingtime"
}

rprompt_online
rprompt_battery
# rprompt_segment black yellow "$(~/.dotfiles/bin/mem)"
# rprompt_segment black green "$(~/.dotfiles/bin/cpu)"
[[ -n "$(~/.dotfiles/bin/vagrant-machines)" ]] && rprompt_segment black cyan "$(~/.dotfiles/bin/vagrant-machines)"
rprompt_segment black white "$(date '+%H:%M:%S')"
rprompt_segment black blue "$(date '+%Y-%m-%d')"
rprompt_end
