#!/bin/zsh

function shade {
	case $1 in
		0)  echo -e "\033[42m \033[0m" ;;
		1)  echo -e "\033[0;33m\033[42m░\033[0m" ;;
		2)  echo -e "\033[0;33m\033[42m▒\033[0m" ;;
		3)  echo -e "\033[0;32m\033[43m▒\033[0m" ;;
		4)  echo -e "\033[0;32m\033[43m░\033[0m" ;;
		5)  echo -e "\033[43m \033[0m" ;;
		6)  echo -e "\033[0;31m\033[43m░\033[0m" ;;
		7)  echo -e "\033[0;31m\033[43m▒\033[0m" ;;
		8)  echo -e "\033[0;33m\033[41m▒\033[0m" ;;
		9)  echo -e "\033[0;33m\033[41m░\033[0m" ;;
		*) echo -e "\033[41m \033[0m" ;;
	esac
}

function set_tmux_env() {
	if [[ $# -lt 2 ]]; then
		echo "Usage:\n$0 <key> <value>"
		return 1
	fi
	tmux setenv $1 $2
}

function get_tmux_env() {
	if [[ $# -lt 1 ]]; then
		echo "Usage:\n$0 <key>"
		return 1
	fi
	keyval=$(tmux showenv $1 2> /dev/null | awk -F '=' '{print $1}')
	echo $keyval
}
