#!/bin/zsh

function shade {
	case $1 in
		0)  echo -e "\033[42m \033[0m" ;;
		1)  echo -e "\033[0;33m\033[42m░\033[0m" ;;
		2)  echo -e "\033[0;33m\033[42m▒\033[0m" ;;
		3)  echo -e "\033[0;32m\033[43m▒\033[0m" ;;
		4)  echo -e "\033[0;32m\033[43m░\033[0m" ;;
		5)  echo -e "\033[43m \033[0m" ;;
		6)  echo -e "\033[0;31m\033[43m░\033[0m" ;;
		7)  echo -e "\033[0;31m\033[43m▒\033[0m" ;;
		8)  echo -e "\033[0;33m\033[41m▒\033[0m" ;;
		9)  echo -e "\033[0;33m\033[41m░\033[0m" ;;
		*) echo -e "\033[41m \033[0m" ;;
	esac
}

function set_tmux_env() {
	if [[ $# -lt 2 ]]; then
		echo "Usage:\n$0 <key> <value>"
		return 1
	fi
	tmux setenv $1 $2
}

function get_tmux_env() {
	if [[ $# -lt 1 ]]; then
		echo "Usage:\n$0 <key>"
		return 1
	fi
	keyval=$(tmux showenv $1 2> /dev/null | awk -F '=' '{print $1}')
	echo $keyval
}

function dotbanner() {
	rainbow '     _     _   ___ _ _         ' '   _| |___| |_|  _|_| |___ ___ ' ' _| . | . |  _|  _| | | -_|_ -|' '|_|___|___|_| |_| |_|_|___|___|'
}

hr() {
	[[ -n "$1" ]] && LMESSAGE="$1 "  || LMESSAGE=""
	[[ -n "$2" ]] && CMESSAGE=" $2 " || CMESSAGE=""
	[[ -n "$3" ]] && RMESSAGE=" $3"  || RMESSAGE=""

	[[ "$4" = <-> ]] && LFG=$FG[$4] || LFG=""
	[[ "$5" = <-> ]] && CFG=$FG[$5] || CFG=""
	[[ "$6" = <-> ]] && RFG=$FG[$6] || RFG=""
	[[ "$7" = <-> ]] && BFG=$FG[$7] || BFG=""

	LLENGTH=${#${LMESSAGE}}
	CLENGTH=${#${CMESSAGE}}
	RLENGTH=${#${RMESSAGE}}

	CODD=$(( $CLENGTH%2 ))

	LBAR=$BFG${(l:($COLUMNS/2-$LLENGTH-$CLENGTH/2-$CODD)::-:)}$reset_color
	RBAR=$BFG${(l:($COLUMNS/2-$RLENGTH-$CLENGTH/2)::-:)}$reset_color

	print -P -- "$LFG$LMESSAGE$reset_color$LBAR$CFG$CMESSAGE$reset_color$RBAR$RFG$RMESSAGE$reset_color"
}

rainbow() {
	color=160
	while [[ "$#" -gt 0 ]]; do
		string=$1
		for c in "${(s//)string}"; do
			print -Pn -- $FG[$(printf "%03d" $color)]$c
			color=$(( ($color+1)%196 ))
			[[ $color == 0 ]] && color=160
		done
		print
		shift
	done
	print -P -- $reset_color
}