#!/bin/zsh

CURRENT_TIMESTAMP_PREEXEC="STOP"
function ganglio_preexec {
	CURRENT_TIMESTAMP_PREEXEC=$SECONDS
}

function ganglio_precmd {
	RETVAL=$?
	if [[ "$CURRENT_TIMESTAMP_PREEXEC" -ne "STOP" ]]; then
		let ELAPSED=$SECONDS-$CURRENT_TIMESTAMP_PREEXEC
		if [[ ( "$ELAPSED" -gt "0" ) ]]; then
			elapsed=">>> $ELAPSED"
			
			ecolor=002
			[[ "$RETVAL" -ne "0" ]] && ecolor=001
			
			now=$(date +%H:%M:%S)
			hr $elapsed "" $now $ecolor "" 003 008
			CURRENT_TIMESTAMP_PREEXEC="STOP"
		fi
	fi
	CURRENT_TIMESTAMP_PREEXEC="STOP"
}

# Load required functions.
autoload -Uz add-zsh-hook

# Add hook for calling git-info before each command.
add-zsh-hook preexec ganglio_preexec
add-zsh-hook precmd ganglio_precmd
